---
version: '3.5'

networks:
  eacloud_network:
    name: eacloud_network

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    networks:
      - eacloud_network
    volumes:
      - C:/Users/BhavyaSingh/Documents/apmm-workspace/POC/eacloud/src/main/resources/prometheus.yml:/app/prometheus.yml

  eacloud:
    image: eacloud
    container_name: eacloud
    build:
      context: .
    depends_on:
      - prometheus
    ports:
      - 8090:8090
    networks:
      - eacloud_network

